<?php
    $title = "History - UNIX Survival Guide by the Pina Koalas - ISTE240";
    $path = "./";
    include($path . "assets/inc/header.php");
?>
<div>
    <p>The Unix operating system was created shortly after the Multiplexed Information and Computing Service (MULTICS) was. The MULTICS project which started in the mid 1960s, was worked on by General Electric, Massachusetts Institute for Technology, and Bell Laboratories. Ultimately, Bell Laboratories left the project in 1969.</p>
    <p>UNIX, a multi user computer operating system, was developed in the late 1960s by a team of computer scientists at AT&T Corporation’s Bell Laboratories. In 1969, computer scientists Ken Thompson and Dennis Ritchie, who wrote the first C compiler, led the team that created the first version of UNIX on a PDP-7 minicomputer. The PDP-7 minicomputer was chosen primarily due to Thompson being familiar with the system since working on it was a hobby of his.</p>
    <p>Thompson had liked the potential of MULTICS, but felt that the same thing could essentially be done in a much simpler way. He wrote Unix’s first version in 1969, and named it Uniplexed Operating and Computing System (UNICS). The name ultimately stuck and eventually got shortened to Unix. By the late 1970s, after the initial creation of UNIX, the team adapted it for another computer and they ported it to the PDP-11. This was the first of what would eventually be many ports of UNIX.</p>
    <p>In the late 20th century, UNIX was used for things such as workstations, Internet servers, and mainframe computers. UNIX is said to be an open system since primary features were its simplicity and portability, meaning that it was able to be used on a variety of different systems. UNIX also was good for multitasking, multi-user capabilities, and had a hierarchical file system.</p>
    <p>One of the biggest reasons Unix is so popular is because of its networking capability. With Unix, networking capability is part of the operating system and is not additional software that needs to be purchased, unlike with some other operating systems. This means that Unix is ideal for connecting to the Internet and world wide email. Since Unix was developed by many different people each with varying needs, it has become an operating system that is incredibly easy to adapt and flexible.</p>
    <p>After Thompson left Bell Laboratories, he taught a UNIX course in the mid-1970s at the University of California at Berkeley. This allowed for students and professors to further enhance UNIX, which led to a version of UNIX called Berkeley Software Distribution (BSD) being created. This allowed many people to work on and develop the source code  and led to the creation of C shell, the vi editor, Sendmail, virtual memory, and TCP/IP support.</p>
    <p>Since AT&T continued to work on UNIX, they released a new version of UNIX called System V in 1983. Other companies such as Sun Microsystems, Inc., and Silicon Graphics, Inc., also created UNIX versions as well as continued to develop UNIX which allowed for it to stay relevant. Since UNIX was incredibly successful, it was used as the inspiration for many free open-source operating systems, including Linux, which has mostly replaced UNIX in recent years.</p>
</div>
<?php
    include($path . "assets/inc/footer.php");
?>